
// This file has been generated by the GUI designer. Do not modify.
namespace View
{
	public partial class GUIStatementDialog
	{
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button button_compound;
		
		private global::Gtk.Button button_assign;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button button_print;
		
		private global::Gtk.Button button_if;
		
		private global::Gtk.Button button_fork;
		
		private global::Gtk.Button button_lock_enter;
		
		private global::Gtk.Button button_lock_exit;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label_value;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget View.GUIStatementDialog
			this.Name = "View.GUIStatementDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.AllowShrink = true;
			// Internal child View.GUIStatementDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_compound = new global::Gtk.Button ();
			this.button_compound.CanFocus = true;
			this.button_compound.Name = "button_compound";
			this.button_compound.UseUnderline = true;
			this.button_compound.Label = global::Mono.Unix.Catalog.GetString ("Compound");
			this.hbox2.Add (this.button_compound);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_compound]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_assign = new global::Gtk.Button ();
			this.button_assign.CanFocus = true;
			this.button_assign.Name = "button_assign";
			this.button_assign.UseUnderline = true;
			this.button_assign.Label = global::Mono.Unix.Catalog.GetString ("Assign");
			this.hbox2.Add (this.button_assign);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_assign]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button_print = new global::Gtk.Button ();
			this.button_print.CanFocus = true;
			this.button_print.Name = "button_print";
			this.button_print.UseUnderline = true;
			this.button_print.Label = global::Mono.Unix.Catalog.GetString ("Print");
			this.hbox3.Add (this.button_print);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_print]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button_if = new global::Gtk.Button ();
			this.button_if.CanFocus = true;
			this.button_if.Name = "button_if";
			this.button_if.UseUnderline = true;
			this.button_if.Label = global::Mono.Unix.Catalog.GetString ("If");
			this.hbox3.Add (this.button_if);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_if]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(1));
			// Container child hbox3.Gtk.Box+BoxChild
			this.button_fork = new global::Gtk.Button ();
			this.button_fork.CanFocus = true;
			this.button_fork.Name = "button_fork";
			this.button_fork.UseUnderline = true;
			this.button_fork.Label = global::Mono.Unix.Catalog.GetString ("Fork");
			this.hbox3.Add (this.button_fork);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_fork]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_lock_enter = new global::Gtk.Button ();
			this.button_lock_enter.CanFocus = true;
			this.button_lock_enter.Name = "button_lock_enter";
			this.button_lock_enter.UseUnderline = true;
			this.button_lock_enter.Label = global::Mono.Unix.Catalog.GetString ("Lock Enter");
			this.hbox2.Add (this.button_lock_enter);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_lock_enter]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_lock_exit = new global::Gtk.Button ();
			this.button_lock_exit.CanFocus = true;
			this.button_lock_exit.Name = "button_lock_exit";
			this.button_lock_exit.UseUnderline = true;
			this.button_lock_exit.Label = global::Mono.Unix.Catalog.GetString ("Lock Exit");
			this.hbox2.Add (this.button_lock_exit);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_lock_exit]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			w1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child View.GUIStatementDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.label_value = new global::Gtk.Label ();
			this.label_value.Name = "label_value";
			this.label_value.Xalign = 0F;
			this.label_value.LabelProp = global::Mono.Unix.Catalog.GetString ("<value>");
			this.hbox5.Add (this.label_value);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label_value]));
			w12.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.BorderWidth = ((uint)(3));
			this.buttonOk.Label = "gtk-ok";
			this.hbox5.Add (this.buttonOk);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w11.Add (this.hbox5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.hbox5]));
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 405;
			this.DefaultHeight = 71;
			this.Show ();
			this.Close += new global::System.EventHandler (this.OnClose);
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button_compound.Clicked += new global::System.EventHandler (this.OnButtonCompoundClicked);
			this.button_assign.Clicked += new global::System.EventHandler (this.OnButtonAssignClicked);
			this.button_print.Clicked += new global::System.EventHandler (this.OnButtonPrintClicked);
			this.button_if.Clicked += new global::System.EventHandler (this.OnButtonIfClicked);
			this.button_fork.Clicked += new global::System.EventHandler (this.OnButtonForkClicked);
			this.button_lock_enter.Clicked += new global::System.EventHandler (this.OnButtonLockEnterClicked);
			this.button_lock_exit.Clicked += new global::System.EventHandler (this.OnButtonLockExitClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
