
// This file has been generated by the GUI designer. Do not modify.
namespace View
{
	public partial class GUIDebugDialog
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button button_all;
		
		private global::Gtk.Button button_next;
		
		private global::Gtk.Button button_reload;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView text_output;
		
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget View.GUIDebugDialog
			this.Name = "View.GUIDebugDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.DefaultWidth = 1280;
			this.DefaultHeight = 720;
			// Internal child View.GUIDebugDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_all = new global::Gtk.Button ();
			this.button_all.CanFocus = true;
			this.button_all.Name = "button_all";
			this.button_all.UseUnderline = true;
			this.button_all.Label = global::Mono.Unix.Catalog.GetString ("Debug All");
			this.hbox1.Add (this.button_all);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_all]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_next = new global::Gtk.Button ();
			this.button_next.CanFocus = true;
			this.button_next.Name = "button_next";
			this.button_next.UseUnderline = true;
			this.button_next.Label = global::Mono.Unix.Catalog.GetString ("Debug Next");
			this.hbox1.Add (this.button_next);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_next]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button_reload = new global::Gtk.Button ();
			this.button_reload.CanFocus = true;
			this.button_reload.Name = "button_reload";
			this.button_reload.UseUnderline = true;
			this.button_reload.Label = global::Mono.Unix.Catalog.GetString ("Reload");
			this.hbox1.Add (this.button_reload);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button_reload]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox6.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.text_output = new global::Gtk.TextView ();
			this.text_output.CanFocus = true;
			this.text_output.Name = "text_output";
			this.GtkScrolledWindow.Add (this.text_output);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w7.Position = 1;
			w1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox6]));
			w8.Position = 0;
			// Internal child View.GUIDebugDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.Close += new global::System.EventHandler (this.OnClose);
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button_all.Clicked += new global::System.EventHandler (this.OnButtonAllClicked);
			this.button_next.Clicked += new global::System.EventHandler (this.OnButtonNextClicked);
			this.button_reload.Clicked += new global::System.EventHandler (this.OnButtonReloadClicked);
			this.text_output.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnTextOutputSizeAllocated);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
		}
	}
}
