#!/bin/bash

echo Status: 200 OK
echo Content-Type: text/html
echo
echo

echo "<html><head></head>"
echo "<body>"
echo "AUTH_TYPE=" $AUTH_TYPE "<br />"
echo "CONTENT_LENGTH=" $CONTENT_LENGTH "<br />"
echo "CONTENT_TYPE=" $CONTENT_TYPE "<br />"
echo "GATEWAY_INTERFACE=" $GATEWAY_INTERFACE "<br />"
echo "PATH_INFO=" $PATH_INFO "<br />"
echo "QUERY_STRING=" $QUERY_STRING "<br />"
echo "REMOTE_ADDR=" $REMOTE_ADDR "<br />"
echo "REMOTE_HOST=" $REMOTE_HOST "<br />"
echo "REMOTE_USER=" $REMOTE_USER "<br />"
echo "REQUEST_METHOD=" $REQUEST_METHOD "<br />"
echo "SCRIPT_NAME=" $SCRIPT_NAME "<br />"
echo "SERVER_NAME=" $SERVER_NAME "<br />"
echo "SERVER_PORT=" $SERVER_PORT "<br />"
echo "SERVER_PROTOCOL=" $SERVER_PROTOCOL "<br />"
echo "SERVER_SOFTWARE=" $SERVER_SOFTWARE "<br />"
echo "</body></html>"

